import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main(){
    const set = await prisma.GundamArsenalBaseSet.createMany({
        data: [
            {name: "Season:01", shortName: "AB01"},
            {name: "Season:02", shortName: "AB02"},
            {name: "Season:03", shortName: "AB03"},
            {name: "Season:04", shortName: "AB04"},
            {name: "Linxtage Season:01", shortName: "LX01"},
            {name: "Linxtage Season:02", shortName: "LX02"},
            {name: "Linxtage Season:03", shortName: "LX03"},
            {name: "Linxtage Season:04", shortName: "LX04"},
            {name: "Unitribe Season:01", shortName: "UT01"},
            {name: "Unitribe Season:02", shortName: "UT02"},
            {name: "Arsenal Rare Season 1", shortName: "AR01"},
            {name: "Arsenal Rare Season 2", shortName: "AR02"},
            {name: "Arsenal Rare Season 3", shortName: "AR03"},
            {name: "Arsenal Rare Season 4", shortName: "AR04"},
            {name: "Linxtage Rare Season 1", shortName: "LXR01"},
            {name: "Linxtage Rare Season 2", shortName: "LXR02"},
            {name: "Linxtage Rare Season 3", shortName: "LXR03"},
            {name: "Linxtage Rare Season 4", shortName: "LXR04"},
            {name: "Unitribe Rare Season 1", shortName: "UTB01"},
            {name: "Starter Deck: Mobile Suit Gundam SEED", shortName: "ST01"},
            {name: "Starter Deck: Mobile Suit Gundam SEED Vol 2", shortName: "ST03"},
            {name: "Starter Deck: Mobile Suit Gundam Iron-Blooded Orphans", shortName: "ST02"},
            {name: "Booster Pack: Mobile Suit Gundam SEED series", shortName: "BP01"},
            {name: "Promotion", shortName: "PR"},
            {name: "Location Test", shortName: "TEST"}
        ]
    })
    const link = await prisma.GundamArsenalBaseLink.createMany({
        data:[
            {linkAbility: "Mobile Suit Gundam", linkEffect: "[Mobility] increases slightly", requirement: "3 or more in deck"},
            {linkAbility: "The 08th MS Team", linkEffect: "[Long Range Atk] increases slightly", requirement: "3 or more in deck"},
            {linkAbility: "MS IGLOO", linkEffect: "[Short Range Atk] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Mobile Suit Gundam Gaiden", linkEffect: "[Short Range Atk] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Mobile Suit Gundam: Cucuruz Doan's Island", linkEffect: "[Short Range Atk] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Thunderbolt", linkEffect: "[Long Range Atk] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "MSV", linkEffect: "[Long Range Atk] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "THE BLUE DESTINY", linkEffect: "[Short Range Atk] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "U.C. ENGAGE", linkEffect: "[Mobility] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Mobile Suit Gundam 0080: War in the Pocket", linkEffect: "[HP] increases slightly", requirement: "3 or more in deck"},
            {linkAbility: "Gundam 0083", linkEffect:"[Mobiliity] increases slightly", requirement: "3 or more in deck"},
            {linkAbility: "Mobile Suit Zeta Gundam", linkEffect: "[Long Range Atk] increases slightly", requirement: "3 or more in deck"},
            {linkAbility: "Mobile Suit Gundam ZZ", linkEffect: "[HP] increases slightly", requirement: "3 or more in deck"},
            {linkAbility: "Char's Counterattack", linkEffect: "[Long Range Atk] increases slightly", requirement: "3 or more in deck"},
            {linkAbility: "Mobile Suit Gundam F91", linkEffect: "[Mobility] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Gundam UC", linkEffect: "[Mobility] increases slightly", requirement: "3 or more in deck"},
            {linkAbility: "Across The Sky", linkEffect: "[Mobility] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "G Gundam", linkEffect: "[Short Range Atk] increases slightly", requirement: "3 or more in deck"},
            {linkAbility: "Gundam Wing", linkEffect: "[Mobility] increases slightly", requirement: "3 or more in deck"},
            {linkAbility: "After War Gundam X", linkEffect: "[Long Range Atk] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Gundam SEED", linkEffect: "[Mobility] increases slightly", requirement: "3 or more in deck"},
            {linkAbility: "SEED DESTINY", linkEffect: "[HP] increases slightly", requirement: "3 or more in deck"},
            {linkAbility: "SEED FREEDOM", linkEffect: "[Mobiblity] increases slightly", requirement: "3 or more in deck"},
            {linkAbility: "SEED ASTRAY", linkEffect: "[Short Range Atk] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "STARGAZER", linkEffect: "[Long Range Atk] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Gundam 00", linkEffect: "[Mobility] increases slightly", requirement: "3 or more in deck"},
            {linkAbility: "Gundam AGE", linkEffect: "[Long Range Atk] increases slightly",  requirement: "3 or more in deck"},
            {linkAbility: "Iron-Blooded Orphans", linkEffect: "[Short Range Atk] increases slightly", requirement: "3 or more in deck"},
            {linkAbility: "Urdr-Hunt", linkEffect: "[Short Range Atk] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Witch of Mercury", linkEffect: "[Mobility] increases slightly", requirement: "3 or more in deck"},
            {linkAbility: "Build Fighters", linkEffect: "[Mobility] increases slightly", requirement: "3 or more in deck"},
            {linkAbility: "TRY", linkEffect: "[HP] increases slightly", requirement: "3 or more in deck"},
            {linkAbility: "Build Divers", linkEffect: "[HP] increases slightly", requirement: "3 or more in deck"},
            {linkAbility: "Re:RISE", linkEffect: "[Long Range Atk] increases slightly", requirement: "3 or more in deck"},
            {linkAbility: "Build Metaverse", linkEffect: "[HP] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "N-EXTREME", linkEffect: "[HP] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Psycho-Frame User", linkEffect: "[Long Range Atk] increases slightly", requirement: "3 or more in deck"},
            {linkAbility: "Its Name Is Gundam", linkEffect: "[Mobility] increases slightly", requirement: "3 or more in deck"},
            {linkAbility: "Newtype's Potential", linkEffect: "[Mobility] increases slightly", requirement: "3 or more in deck"},
            {linkAbility: "Veteran's Skill", linkEffect: "[Short Range Atk] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Resilient Iron Flower", linkEffect: "[Short Range Atk] increases slightly", requirement: "3 or more in deck"},
            {linkAbility: "Skillful Tactics", linkEffect: "[Long Range Atk] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Black Tri-Stars", linkEffect: "[Long Range Atk][Short Range Atk] increases slightly", requirement: "3 or more in deck"},
            {linkAbility: "Pitch-Black Warrior", linkEffect: "[Mobility] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Red Pride", linkEffect: "[Mobility] increases slightly", requirement: "3 or more in deck"},
            {linkAbility: "Power of Personalized Units", linkEffect: "[Short Range Atk] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Stolen Machine", linkEffect: "[Long Range Atk] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Excellent Close Combat Sense", linkEffect: "[Short Range Atk] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Excellent Sharpshooting Sense", linkEffect: "[Long Range Atk] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Ground Combat Specialization", linkEffect: "[Mobility] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Transformable Mobile Suit Fighter", linkEffect: "Special strategy card enabled for use", requirement: "3 or more in deck"},
            {linkAbility: "Trans-Am System", linkEffect: "Special strategy card enabled for use", requirement: "2 or more in deck"},
            {linkAbility: "Gundam Meister", linkEffect: "[Mobility] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Piercing Power of Live Ammunition", linkEffect: "[Long Range Atk] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Distance-Closing Close Combatants", linkEffect: "[Short Range Atk] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Distance-Gaining Sharpshooters", linkEffect: "[Long Range Atk] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Outstanding Officer", linkEffect: "[Mobility] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Those who stole Gundams", linkEffect: "[HP] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Top Priority Mission", linkEffect: "[Mobility] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Mass Produced Unit", linkEffect: "[Mobility] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Ability of Custom Units", linkEffect: "[Long Range Atk] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "All Range Weapon", linkEffect: "[Long Range Atk] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Indominatable Will", linkEffect: "[HP] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Power to Change War", linkEffect: "[Long Range Atk][Short Range Atk] increases slightly", requirement: "4 or more in deck"},
            {linkAbility: "Sturdy Armor", linkEffect: "[HP] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Terrible Fate", linkEffect: "[Mobility] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Unrivaled Power", linkEffect: "[Long Range Atk][Short Range Atk] increases slightly", requirement: "4 or more in deck"},
            {linkAbility: "Excellent Insight", linkEffect: "[Long Range Atk][Short Range Atk] increases slightly", requirement: "4 or more in deck"},
            {linkAbility: "Zaku Zaku Zaku", linkEffect: "[HP] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Underwater Fighter", linkEffect: "[Short Range Atk][HP] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Training Suits", linkEffect: "[HP] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Wolf's Roar", linkEffect: "[Short Range Atk][HP] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Clash of Knights", linkEffect: "[Short Range Atk][HP] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Overwhelming Long Range Attacks", linkEffect: "[Mobility][Long Range Atk] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Witch of Earth", linkEffect: "[Long Range Atk][Short Range Atk] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Varied Strategies", linkEffect: "[Long Range Atk][Short Range Atk] increases slightly", requirement: "4 or more in deck"},
            {linkAbility: "Destructive Close Combatant", linkEffect: "[Short Range Atk] increases moderately", requirement: "Deck contains 2 or more [Short Range] Mobile Suits"},
            {linkAbility: "Sniping Sharpshooter", linkEffect: "[Long Range Atk] increases moderately", requiement: "Deck contains 2 or more [Long Range] Mobile Suits"},
            {linkAbility: "High Mobility Sharpshooter", linkEffect: "[Long Range Atk] increases moderately", requirement: "Deck contains 2 or more [Mobility] Mobile Suits"},
            {linkAbility: "High Speed Close Combatant", linkEffect: "[Short Range Atk] increases moderately", requirement: "Deck contains 2 or more [Mobility] Mobile Suits"},
            {linkAbility: "Overwhelming Power of Extermination", linkEffect: "Deals moderately increased damage to Exterminate units", requirement: "Deck contains 3 or more [Exterminate] Pilots"},
            {linkAbility: "Complete Suppression", linkEffect: "[Repair Time] decreases", requirement: "Deck contains 3 or more [Suppress] Pilots"},
            {linkAbility: "Flawless Defensive Formation", linkEffect: "[Defending Base's Attack Power] increases moderately", requirement: "Deck contains 2 or more [Defense] Pilots"},
            {linkAbility: "Trans Am's True Value", linkEffect: "[Long Range Atk][Short Range Atk] increases slightly, special strategy card enabled for use", requirement: "2 or more in deck"},
            {linkAbility: "Champion", linkEffect: "[Long Range Atk][HP] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Decisive Blow", linkEffect: "[Mobility][Long Range Atk] increases slightly", requirement: "4 or more in deck"},
            {linkAbility: "Destined for Battle", linkEffect: "[Mobility][HP] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Fascinating Stage", linkEffect: "[Mobility][HP] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Return of the Red Comet", linkEffect: "[Mobility][Short Range Atk] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "White Wolf", linkEffect: "[Short Range Atk][HP] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "Aggressive Assailant", linkEffect: "[Mobility][Short Range Atk] increases slightly", requirement: "4 or more in deck"},
            {linkAbility: "Black Thread", linkEffect: "[HP] increases slightly", requirement: "2 or more in deck"},
            {linkAbility: "System's Guidance", linkEffect: "[HP][SP Power] increases slightly", requirement: "2 or more in deck"},

        ]
    })
    const card = await prisma.GundamArsenalBaseCard.createMany({
        data:[
            {
                name: "Gundam",
                cardType: "Mobile Suit",
                msType: "Short Range",
                plType: null,
                parallel: false,
                cost: 4,
                rarity: "M",
                mobility: 200,
                longRange: 110,
                shortRange: 370,
                hp: 380,
                earthMod: "A",
                spaceMod: "A",
                desertMod: "C",
                waterMod: "A",
                series: "Mobile Suit Gundam",
                mainWeapon: "Beam Saber",
                mainWeaponRange: 1,
                mainWeaponType: "Short Range",
                subWeapon: "Beam Rifle",
                subWeaponRange: 3,
                subWeaponType: "Long Range",
                msAbility: "Consecutive Attacks",
                msActiveCondition: "Manual Activation",
                msTargetType: "Single Target (Enemy)",
                msAbilityRange: 2,
                msAbilityCost: 3,
                msAbilityDesc: "Deal damage to the target.",
                spAbilityName: "Beam Saber Heavy Strike",
                spAbilityTargetType: "Single Target (Enemy)",
                spAbilityRange: 2,
                spAbilityCost: 2,
                spAbilityDamage: 3400,
                spAbilityDesc: "Deal short range damage to the target.",
                linkIds: {
                    connect: [{linkAbility: "Mobile Suit Gundam"}, {linkAbility: "Its Name Is Gundam"}]
                },
                set: {connect: {shortName: "AB01"}},
                setNum: "-001",
                suitCode: "RX-78-2",
                imageUrlFront: "../public/gundam-ab/ab01/AB01-001_front.png",
                imageUrlBack: "../public/gundam-ab/ab01/AB01-001_back.png"
            },
            {
                name: "Gundam",
                cardType: "Mobile Suit",
                msType: "Long Range",
                plType: null,
                parallel: false,
                cost: 5,
                rarity: "C",
                mobility: 110,
                longRange: 190,
                shortRange: 70,
                hp: 170,
                earthMod: "A",
                spaceMod: "A",
                desertMod: "C",
                waterMod: "A",
                series: "Mobile Suit Gundam",
                mainWeapon: "Beam Rifle",
                mainWeaponRange: 3,
                mainWeaponType: "Long Range",
                subWeapon: "Beam Saber",
                subWeaponRange: 1,
                subWeaponType: "Short Range",
                msAbility: "Rally (Long Range Atk)",
                msActiveCondition: "Manual Activation",
                msTargetType: "Area of Effect (Ally)",
                msAbilityRange: null,
                msAbilityCost: 4,
                msAbilityDesc: "For 30 seconds, slightly increases the [Long Range Atk] of all allies around the user",
                spAbilityName: "Beam Rifle Attack",
                spAbilityTargetType: "Single Target (Enemy)",
                spAbilityRange: 3,
                spAbilityCost: 2,
                spAbilityDamage: 3200,
                spAbilityDesc: "Deal long range damage to the target.",
                linkIds: {
                    connect: [{linkAbility: "Mobile Suit Gundam"}, {linkAbility: "Its Name Is Gundam"}]
                },
                set: {connect: {shortName: "AB01"}},
                setNum: "-002",
                suitCode: "RX-78-2",
                imageUrlFront: "../public/gundam-ab/ab01/AB01-002_front.png",
                imageUrlBack: "../public/gundam-ab/ab01/AB01-002_back.png"
            },
            {
                name: "Guncannon",
                cardType: "Mobile Suit",
                msType: "Long Range",
                plType: null,
                parallel: false,
                cost: 2,
                rarity: "R",
                mobility: 110,
                longRange: 190,
                shortRange: 90,
                hp: 110,
                earthMod: "A",
                spaceMod: "A",
                desertMod: "C",
                waterMod: "C",
                series: "Mobile Suit Gundam",
                mainWeapon: "240mm Cannon",
                mainWeaponRange: 4,
                mainWeaponType: "Long Range",
                subWeapon: "Beam Rifle",
                subWeaponRange: 3,
                subWeaponType: "Short Range",
                msAbility: "Artillery Fire",
                msActiveCondition: "Manual Activation",
                msTargetType: "Area of Effect (Enemy)",
                msAbilityRange: 5,
                msAbilityCost: 4,
                msAbilityDesc: "Deals damage to all enemies in a small area in front of the user",
                spAbilityName: "240mm Cannon Artillery Fire",
                spAbilityTargetType: "Single Target (Enemy)",
                spAbilityRange: 4,
                spAbilityCost: 2,
                spAbilityDamage: 3000,
                spAbilityDesc: "Deal long range damage to the target.",
                linkIds: {
                    connect: [{linkAbility: "Mobile Suit Gundam"}]
                },
                set: {connect: {shortName: "AB01"}},
                setNum: "-003",
                suitCode: "RX-77-2",
                imageUrlFront: "../public/gundam-ab/ab01/AB01-003_front.png",
                imageUrlBack: "../public/gundam-ab/ab01/AB01-003_back.png"
            },
            {
                name: "Guntank",
                cardType: "Mobile Suit",
                msType: "Long Range",
                plType: null,
                parallel: false,
                cost: 5,
                rarity: "C",
                mobility: 60,
                longRange: 280,
                shortRange: 50,
                hp: 180,
                earthMod: "S",
                spaceMod: "C",
                desertMod: "S",
                waterMod: "C",
                series: "Mobile Suit Gundam",
                mainWeapon: "120mm Cannon",
                mainWeaponRange: 4,
                mainWeaponType: "Long Range",
                subWeapon: "Bop Missile Launcher",
                subWeaponRange: 2,
                subWeaponType: "Short Range",
                msAbility: "Artillery Fire",
                msActiveCondition: "Manual Activation",
                msTargetType: "Area of Effect (Enemy)",
                msAbilityRange: 5,
                msAbilityCost: 4,
                msAbilityDesc: "Deals damage to all enemies in a small area in front of the user",
                spAbilityName: "120mm Cannon Artillery Fire",
                spAbilityTargetType: "Area of Effect (Enemy)",
                spAbilityRange: 4,
                spAbilityCost: 3,
                spAbilityDamage: 3400,
                spAbilityDesc: "Deals damage to all enemies in a small area where the target is located",
                linkIds: {
                    connect: [{linkAbility: "Mobile Suit Gundam"}]
                },
                set: {connect: {shortName: "AB01"}},
                setNum: "-004",
                suitCode: "RX-75",
                imageUrlFront: "../public/gundam-ab/ab01/AB01-004_front.png",
                imageUrlBack: "../public/gundam-ab/ab01/AB01-004_back.png"
            },
            {
                name: "GM",
                cardType: "Mobile Suit",
                msType: "Long Range",
                plType: null,
                parallel: false,
                cost: 2,
                rarity: "C",
                mobility: 80,
                longRange: 160,
                shortRange: 60,
                hp: 140,
                earthMod: "A",
                spaceMod: "A",
                desertMod: "C",
                waterMod: "C",
                series: "Mobile Suit Gundam",
                mainWeapon: "Beam Spray Gun",
                mainWeaponRange: 3,
                mainWeaponType: "Long Range",
                subWeapon: "Bean Saber",
                subWeaponRange: 1,
                subWeaponType: "Short Range",
                msAbility: "Call Reinforcements (Exterminate)",
                msActiveCondition: "Manual Activation",
                msTargetType: "Special (Self)",
                msAbilityRange: null,
                msAbilityCost: 3,
                msAbilityDesc: "Summons an ally unit with [Exterminate] typing nearby. Only 3 summoned units can be on the field at once.",
                spAbilityName: "Beam Spray Gun Attack",
                spAbilityTargetType: "Single Target (Enemy)",
                spAbilityRange: 3,
                spAbilityCost: 2,
                spAbilityDamage: 3000,
                spAbilityDesc: "Deals damage to the target.",
                linkIds: {
                    connect: [{linkAbility: "Mobile Suit Gundam"}]
                },
                set: {connect: {shortName: "AB01"}},
                setNum: "-005",
                suitCode: "RX-79",
                imageUrlFront: "../public/gundam-ab/ab01/AB01-005_front.png",
                imageUrlBack: "../public/gundam-ab/ab01/AB01-005_back.png"
            },
            {
                name: "Zaku II",
                cardType: "Mobile Suit",
                msType: "Mobility",
                plType: null,
                parallel: false,
                cost: 2,
                rarity: "C",
                mobility: 120,
                longRange: 230,
                shortRange: 120,
                hp: 120,
                earthMod: "A",
                spaceMod: "A",
                desertMod: "C",
                waterMod: "C",
                series: "Mobile Suit Gundam",
                mainWeapon: "Zaku Machine Gun",
                mainWeaponRange: 2,
                mainWeaponType: "Long Range",
                subWeapon: "Heat Tomahawk",
                subWeaponRange: 1,
                subWeaponType: "Short Range",
                msAbility: "Grenade Throw",
                msActiveCondition: "Manual Activation",
                msTargetType: "Area of Effect (Enemy)",
                msAbilityRange: 3,
                msAbilityCost: 3,
                msAbilityDesc: "Deals damage to all enemies in a small area where the target is located",
                spAbilityName: "Zaku Machine Gun Attack",
                spAbilityTargetType: "Single Target (Enemy)",
                spAbilityRange: 3,
                spAbilityCost: 2,
                spAbilityDamage: 3000,
                spAbilityDesc: "Deals long range enemy to the target.",
                linkIds: {
                    connect: [{linkAbility: "Mobile Suit Gundam"}]
                },
                set: {connect: {shortName: "AB01"}},
                setNum: "-006",
                suitCode: "MS-06F",
                imageUrlFront: "../public/gundam-ab/ab01/AB01-006_front.png",
                imageUrlBack: "../public/gundam-ab/ab01/AB01-006_back.png"
            },
            {
                name: "Char's Zaku II",
                cardType: "Mobile Suit",
                msType: "Long Range",
                plType: null,
                parallel: false,
                cost: 5,
                rarity: "M",
                mobility: 190,
                longRange: 360,
                shortRange: 110,
                hp: 240,
                earthMod: "A",
                spaceMod: "S",
                desertMod: "C",
                waterMod: "C",
                series: "Mobile Suit Gundam",
                mainWeapon: "Zaku Bazooka",
                mainWeaponRange: 3,
                mainWeaponType: "Long Range",
                subWeapon: "Heat Tomahawk",
                subWeaponRange: 1,
                subWeaponType: "Short Range",
                msAbility: "Call Reinforcements (Exterminate)",
                msActiveCondition: "Manual Activation",
                msTargetType: "Special (Self)",
                msAbilityRange: null,
                msAbilityCost: 3,
                msAbilityDesc: "Summons an ally unit with [Exterminate] typing nearby. Only 3 summoned units can be on the field at once.",
                spAbilityName: "Zaku Bazooka Attack",
                spAbilityTargetType: "Single Target (Enemy)",
                spAbilityRange: 3,
                spAbilityCost: 3,
                spAbilityDamage: 3800,
                spAbilityDesc: "Deals long range damage to the target.",
                linkIds: {
                    connect: [{linkAbility: "Mobile Suit Gundam"}, {linkAbility: "Red Pride"}]
                },
                set: {connect: {shortName: "AB01"}},
                setNum: "-007",
                suitCode: "MS-06S",
                imageUrlFront: "../public/gundam-ab/ab01/AB01-007_front.png",
                imageUrlBack: "../public/gundam-ab/ab01/AB01-007_back.png"
            },
            {
                name: "Gouf",
                cardType: "Mobile Suit",
                msType: "Short Range",
                plType: null,
                parallel: false,
                cost: 2,
                rarity: "M",
                mobility: 210,
                longRange: 0,
                shortRange: 260,
                hp: 330,
                earthMod: "S",
                spaceMod: "C",
                desertMod: "A",
                waterMod: "C",
                series: "Mobile Suit Gundam",
                mainWeapon: "Heat Saber",
                mainWeaponRange: 1,
                mainWeaponType: "Short Range",
                subWeapon: "Shield",
                subWeaponRange: null,
                subWeaponType: "Defense",
                msAbility: "Hindering Strike (Mobility)",
                msActiveCondition: "Manual Activation",
                msTargetType: "Single Target (Enemy)",
                msAbilityRange: 2,
                msAbilityCost: 3,
                msAbilityDesc: "Deals damage to locked-on target. For 20 seconds, the target's [Mobility] is moderately decreased.",
                spAbilityName: "Heat Saber Strong Strike",
                spAbilityTargetType: "Single Target (Enemy)",
                spAbilityRange: 2,
                spAbilityCost: 2,
                spAbilityDamage: 3300,
                spAbilityDesc: "Deals short range damage to the target.",
                linkIds: {
                    connect: [{linkAbility: "Mobile Suit Gundam"}]
                },
                set: {connect: {shortName: "AB01"}},
                setNum: "-008",
                suitCode: "MS-07B",
                imageUrlFront: "../public/gundam-ab/ab01/AB01-008_front.png",
                imageUrlBack: "../public/gundam-ab/ab01/AB01-008_back.png"
            },
            {
                name: "Gouf",
                cardType: "Mobile Suit",
                msType: "Mobility",
                plType: null,
                parallel: false,
                cost: 3,
                rarity: "R",
                mobility: 210,
                longRange: 190,
                shortRange: 150,
                hp: 170,
                earthMod: "S",
                spaceMod: "C",
                desertMod: "A",
                waterMod: "C",
                series: "Mobile Suit Gundam",
                mainWeapon: "Finger Vulcan",
                mainWeaponRange: 2,
                mainWeaponType: "Long Range",
                subWeapon: "Heat Saber",
                subWeaponRange: 1,
                subWeaponType: "Short Range",
                msAbility: "Resupply",
                msActiveCondition: "Manual Activation",
                msTargetType: "Area of Effect (Ally)",
                msAbilityRange: null,
                msAbilityCost: 4,
                msAbilityDesc: "Restores a moderate amount of HP to all allies within a large area around the user.",
                spAbilityName: "Finger Vulcan Attack",
                spAbilityTargetType: "Single Target (Enemy)",
                spAbilityRange: 3,
                spAbilityCost: 2,
                spAbilityDamage: 3200,
                spAbilityDesc: "Deals short range damage to the target.",
                linkIds: {
                    connect: [{linkAbility: "Mobile Suit Gundam"}]
                },
                set: {connect: {shortName: "AB01"}},
                setNum: "-009",
                suitCode: "MS-07B",
                imageUrlFront: "../public/gundam-ab/ab01/AB01-009_front.png",
                imageUrlBack: "../public/gundam-ab/ab01/AB01-009_back.png"
            },
            {
                name: "Dom",
                cardType: "Mobile Suit",
                msType: "Mobility",
                plType: null,
                parallel: false,
                cost: 2,
                rarity: "R",
                mobility: 190,
                longRange: 110,
                shortRange: 180,
                hp: 200,
                earthMod: "S",
                spaceMod: "C",
                desertMod: "A",
                waterMod: "C",
                series: "Mobile Suit Gundam",
                mainWeapon: "Heat Saber",
                mainWeaponRange: 1,
                mainWeaponType: "Short Range",
                subWeapon: "Giant Bazooka",
                subWeaponRange: 3,
                subWeaponType: "Long Range",
                msAbility: "Blinding Flash(Point Blank)",
                msActiveCondition: "Manual Activation",
                msTargetType: "Area of Effect (Enemy)",
                msAbilityRange: 2,
                msAbilityCost: 2,
                msAbilityDesc: "Applies a debuff effect in a cone-shape with the target at the center. For 20 seconds, all affected enemies have slightly decreased [Long Range Atk] and [Short Range Atk].",
                spAbilityName: "Heat Saber Strong Strike",
                spAbilityTargetType: "Single Target (Enemy)",
                spAbilityRange: 2,
                spAbilityCost: 2,
                spAbilityDamage: 3200,
                spAbilityDesc: "Deals short range damage to the target.",
                linkIds: {
                    connect: [{linkAbility: "Mobile Suit Gundam"}, {linkAbility: "Pitch-Black Warrior"}]
                },
                set: {connect: {shortName: "AB01"}},
                setNum: "-010",
                suitCode: "MS-09",
                imageUrlFront: "../public/gundam-ab/ab01/AB01-010_front.png",
                imageUrlBack: "../public/gundam-ab/ab01/AB01-010_back.png"
            },
            {
                name: "Dom",
                cardType: "Mobile Suit",
                msType: "Mobility",
                plType: null,
                parallel: false,
                cost: 3,
                rarity: "R",
                mobility: 200,
                longRange: 100,
                shortRange: 160,
                hp: 170,
                earthMod: "S",
                spaceMod: "C",
                desertMod: "A",
                waterMod: "C",
                series: "Mobile Suit Gundam",
                mainWeapon: "Heat Saber",
                mainWeaponRange: 1,
                mainWeaponType: "Short Range",
                subWeapon: "Giant Bazooka",
                subWeaponRange: 3,
                subWeaponType: "Long Range",
                msAbility: null,
                msActiveCondition: null,
                msTargetType: null,
                msAbilityRange: null,
                msAbilityCost: null,
                msAbilityDesc: null,
                spAbilityName: "Heat Saber Strong Strike",
                spAbilityTargetType: "Single Target (Enemy)",
                spAbilityRange: 2,
                spAbilityCost: 2,
                spAbilityDamage: 3200,
                spAbilityDesc: "Deals short range damage to the target.",
                linkIds: {
                    connect: [{linkAbility: "Mobile Suit Gundam"}, {linkAbility: "Pitch-Black Warrior"}]
                },
                set: {connect: {shortName: "AB01"}},
                setNum: "-011",
                suitCode: "MS-09",
                imageUrlFront: "../public/gundam-ab/ab01/AB01-011_front.png",
                imageUrlBack: "../public/gundam-ab/ab01/AB01-011_back.png"
            },
            {
                name: "Dom",
                cardType: "Mobile Suit",
                msType: "Mobility",
                plType: null,
                parallel: false,
                cost: 2,
                rarity: "R",
                mobility: 240,
                longRange: 190,
                shortRange: 80,
                hp: 80,
                earthMod: "S",
                spaceMod: "C",
                desertMod: "A",
                waterMod: "C",
                series: "Mobile Suit Gundam",
                mainWeapon: "Giant Bazooka",
                mainWeaponRange: 3,
                mainWeaponType: "Long Range",
                subWeapon: "Heat Saber",
                subWeaponRange: 1,
                subWeaponType: "Short Range",
                msAbility: "Rally (Mobility)",
                msActiveCondition: "Manual Activation",
                msTargetType: "Area of Effect (Ally)",
                msAbilityRange: null,
                msAbilityCost: 4,
                msAbilityDesc: "For 30 seconds, all allies within a large area around the user gains slightly increased [Mobility].",
                spAbilityName: "Giant Bazooka Attack",
                spAbilityTargetType: "Single Target (Enemy)",
                spAbilityRange: 3,
                spAbilityCost: 2,
                spAbilityDamage: 3000,
                spAbilityDesc: "Deals long range damage to the target.",
                linkIds: {
                    connect: [{linkAbility: "Mobile Suit Gundam"}, {linkAbility: "Pitch-Black Warrior"}]
                },
                set: {connect: {shortName: "AB01"}},
                setNum: "-012",
                suitCode: "MS-09",
                imageUrlFront: "../public/gundam-ab/ab01/AB01-012_front.png",
                imageUrlBack: "../public/gundam-ab/ab01/AB01-012_back.png"
            },
            {
                name: "Pale Rider",
                cardType: "Mobile Suit",
                msType: "Mobility",
                plType: null,
                parallel: false,
                cost: 3,
                rarity: "M",
                mobility: 290,
                longRange: 230,
                shortRange: 300,
                hp: 220,
                earthMod: "S",
                spaceMod: "B",
                desertMod: "A",
                waterMod: "C",
                series: "Mobile Suit Gundam Gaiden",
                mainWeapon: "Dual Wield Beam Sabers",
                mainWeaponRange: 1,
                mainWeaponType: "Short Range",
                subWeapon: "Vulcan Gun",
                subWeaponRange: 2,
                subWeaponType: "Long Range",
                msAbility: "HADES",
                msActiveCondition: "Manual Activation",
                msTargetType: "Self",
                msAbilityRange: null,
                msAbilityCost: 4,
                msAbilityDesc: "For 30 seconds, attack frequency is moderately increased.",
                spAbilityName: "Double Beam Saber Strong Strike",
                spAbilityTargetType: "Single Target (Enemy)",
                spAbilityRange: 2,
                spAbilityCost: 2,
                spAbilityDamage: 3500,
                spAbilityDesc: "Deals short range damage to the target.",
                linkIds: {
                    connect: [{linkAbility: "Mobile Suit Gundam Gaiden"}]
                },
                set: {connect: {shortName: "AB01"}},
                setNum: "-013",
                suitCode: "RX-80PR",
                imageUrlFront: "../public/gundam-ab/ab01/AB01-013_front.png",
                imageUrlBack: "../public/gundam-ab/ab01/AB01-013_back.png"
            },
            {
                name: "Pale Rider",
                cardType: "Mobile Suit",
                msType: "Long Range Atk",
                plType: null,
                parallel: false,
                cost: 5,
                rarity: "C",
                mobility: 110,
                longRange: 280,
                shortRange: 90,
                hp: 90,
                earthMod: "S",
                spaceMod: "B",
                desertMod: "A",
                waterMod: "C",
                series: "Mobile Suit Gundam Gaiden",
                mainWeapon: "180mm Cannon",
                mainWeaponRange: 4,
                mainWeaponType: "Long Range",
                subWeapon: "90mm Bullpup Machine Gun",
                subWeaponRange: 2,
                subWeaponType: "Short Range",
                msAbility: null,
                msActiveCondition: null,
                msTargetType: null,
                msAbilityRange: null,
                msAbilityCost: null,
                msAbilityDesc: null,
                spAbilityName: "180mm Cannon Attack",
                spAbilityTargetType: "Single Target (Enemy)",
                spAbilityRange: 4,
                spAbilityCost: 2,
                spAbilityDamage: 3100,
                spAbilityDesc: "Deals long range damage to the target.",
                linkIds: {
                    connect: [{linkAbility: "Mobile Suit Gundam Gaiden"}]
                },
                set: {connect: {shortName: "AB01"}},
                setNum: "-014",
                suitCode: "RX-80PR",
                imageUrlFront: "../public/gundam-ab/ab01/AB01-014_front.png",
                imageUrlBack: "../public/gundam-ab/ab01/AB01-014_back.png"
            },
            {
                name: "Unicorn Gundam",
                cardType: "Mobile Suit",
                msType: "Long Range",
                plType: null,
                parallel: false,
                cost: 7,
                rarity: "U",
                mobility: 220,
                longRange: 510,
                shortRange: 240,
                hp: 420,
                earthMod: "A",
                spaceMod: "S",
                desertMod: "C",
                waterMod: "B",
                series: "Gundam UC",
                mainWeapon: "Beam Magnum",
                mainWeaponRange: 3,
                mainWeaponType: "Long Range",
                subWeapon: "Beam Saber",
                subWeaponRange: 1,
                subWeaponType: "Short Range",
                msAbility: "Piercing Shot",
                msActiveCondition: "Manual Activation",
                msTargetType: "Piercing (Enemy)",
                msAbilityRange: 3,
                msAbilityCost: 3,
                msAbilityDesc: "After charging for a moment, fires a piercing long range attack at the target, dealing damage to all enemies in the line of fire.",
                spAbilityName: "Beam Magnum Piercing Shot (Destroy Mode)",
                spAbilityTargetType: "Piercing (Enemy)",
                spAbilityRange: 3,
                spAbilityCost: 3,
                spAbilityDamage: 3700,
                spAbilityDesc: "Transforms to Destroy Mode and fires a piercing attack at the target, dealing damage to all enemies in the line of fire. While in Destroy Mode, abilities are strengthened. This effect ends when this unit retreats.",
                linkIds: {
                    connect: [{linkAbility: "Gundam UC"}, {linkAbility: "Psycho-Frame User"}]
                },
                set: {connect: {shortName: "AB01"}},
                setNum: "-015",
                suitCode: "RX-0",
                imageUrlFront: "../public/gundam-ab/ab01/AB01-015_front.png",
                imageUrlBack: "../public/gundam-ab/ab01/AB01-015_back.png"
            },
            {
                name: "Unicorn Gundam",
                cardType: "Mobile Suit",
                msType: "Long Range",
                plType: null,
                parallel: true,
                cost: 7,
                rarity: "U",
                mobility: 220,
                longRange: 510,
                shortRange: 240,
                hp: 420,
                earthMod: "A",
                spaceMod: "S",
                desertMod: "C",
                waterMod: "B",
                series: "Gundam UC",
                mainWeapon: "Beam Magnum",
                mainWeaponRange: 3,
                mainWeaponType: "Long Range",
                subWeapon: "Beam Saber",
                subWeaponRange: 1,
                subWeaponType: "Short Range",
                msAbility: "Piercing Shot",
                msActiveCondition: "Manual Activation",
                msTargetType: "Piercing (Enemy)",
                msAbilityRange: 3,
                msAbilityCost: 3,
                msAbilityDesc: "After charging for a moment, fires a piercing long range attack at the target, dealing damage to all enemies in the line of fire.",
                spAbilityName: "Beam Magnum Piercing Shot (Destroy Mode)",
                spAbilityTargetType: "Piercing (Enemy)",
                spAbilityRange: 3,
                spAbilityCost: 3,
                spAbilityDamage: 3700,
                spAbilityDesc: "Transforms to Destroy Mode and fires a piercing attack at the target, dealing damage to all enemies in the line of fire. While in Destroy Mode, abilities are strengthened. This effect ends when this unit retreats.",
                linkIds: {
                    connect: [{linkAbility: "Gundam UC"}, {linkAbility: "Psycho-Frame User"}]
                },
                set: {connect: {shortName: "AB01"}},
                setNum: "-015",
                suitCode: "RX-0",
                imageUrlFront: "../public/gundam-ab/ab01/AB01-015_front_p.png",
                imageUrlBack: "../public/gundam-ab/ab01/AB01-015_back_p.png"
            },
            {
                name: "Unicorn Gundam",
                cardType: "Mobile Suit",
                msType: "Mobility",
                plType: null,
                parallel: false,
                cost: 5,
                rarity: "C",
                mobility: 200,
                longRange: 120,
                shortRange: 150,
                hp: 240,
                earthMod: "A",
                spaceMod: "S",
                desertMod: "C",
                waterMod: "B",
                series: "Gundam UC",
                mainWeapon: "Beam Saber",
                mainWeaponRange: 1,
                mainWeaponType: "Short Range",
                subWeapon: "Beam Magnum",
                subWeaponRange: 3,
                subWeaponType: "Long Range",
                msAbility: null,
                msActiveCondition: null,
                msTargetType: null,
                msAbilityRange: null,
                msAbilityCost: null,
                msAbilityDesc: null,
                spAbilityName: "Beam Saber Strong Strike",
                spAbilityTargetType: "Single Target (Enemy)",
                spAbilityRange: 2,
                spAbilityCost: 2,
                spAbilityDamage: 3300,
                spAbilityDesc: "Deals short range damage to the target.",
                linkIds: {
                    connect: [{linkAbility: "Gundam UC"}, {linkAbility: "Its Name Is Gundam"}]
                },
                set: {connect: {shortName: "AB01"}},
                setNum: "-016",
                suitCode: "RX-0",
                imageUrlFront: "../public/gundam-ab/ab01/AB01-016_front.png",
                imageUrlBack: "../public/gundam-ab/ab01/AB01-016_back.png"
            },
            {
                name: "Unicorn Gundam Perfectibility",
                cardType: "Mobile Suit",
                msType: "Short Range",
                plType: null,
                parallel: false,
                cost: 3,
                rarity: "P",
                mobility: 240,
                longRange: 90,
                shortRange: 160,
                hp: 300,
                earthMod: "A",
                spaceMod: "A",
                desertMod: "C",
                waterMod: "B",
                series: "Gundam UC",
                mainWeapon: "Hyper Beam Javelin",
                mainWeaponRange: 1,
                mainWeaponType: "Short Range",
                subWeapon: "Armed Armor BS",
                subWeaponRange: 3,
                subWeaponType: "Long Range",
                msAbility: "Hindering Strike [Mobility]",
                msActiveCondition: "Manual Activation",
                msTargetType: "Single Target (Enemy)",
                msAbilityRange: 1,
                msAbilityCost: 3,
                msAbilityDesc: "Deals damage to the target and moderately decreases their [Mobility] for 20 seconds.",
                spAbilityName: "Hyper Beam Javelin Throw",
                spAbilityTargetType: "Area of Effect (Enemy)",
                spAbilityRange: 2,
                spAbilityCost: 3,
                spAbilityDamage: 3600,
                spAbilityDesc: "Deals short range damage to all enemy units in a small area where the target is located.",
                linkIds: {
                    connect: [{linkAbility: "Gundam UC"}, {linkAbility: "Psycho-Frame User"}]
                },
                set: {connect: {shortName: "AB01"}},
                setNum: "-017",
                suitCode: "RX-0",
                imageUrlFront: "../public/gundam-ab/ab01/AB01-017_front.png",
                imageUrlBack: "../public/gundam-ab/ab01/AB01-017_back.png"
            },
            {
                name: "Unicorn Gundam Perfectibility",
                cardType: "Mobile Suit",
                msType: "Long Range",
                plType: null,
                parallel: false,
                cost: 4,
                rarity: "R",
                mobility: 60,
                longRange: 220,
                shortRange: 130,
                hp: 120,
                earthMod: "A",
                spaceMod: "A",
                desertMod: "C",
                waterMod: "B",
                series: "Gundam UC",
                mainWeapon: "Armed Armor BS",
                mainWeaponRange: 3,
                mainWeaponType: "Long Range",
                subWeapon: "Hyper Beam Javelin",
                subWeaponRange: 1,
                subWeaponType: "Short Range",
                msAbility: "Strengthen [Long Range]",
                msActiveCondition: "Manual Activation",
                msTargetType: "Self",
                msAbilityRange: null,
                msAbilityCost: 3,
                msAbilityDesc: "For 30 seconds, [Long Range Atk] increases slightly.",
                spAbilityName: "Armed Armor BS Attack",
                spAbilityTargetType: "Single Target (Enemy)",
                spAbilityRange: 3,
                spAbilityCost: 2,
                spAbilityDamage: 3200,
                spAbilityDesc: "Deals long range damage to the target.",
                linkIds: {
                    connect: [{linkAbility: "Gundam UC"}, {linkAbility: "Psycho-Frame User"}]
                },
                set: {connect: {shortName: "AB01"}},
                setNum: "-018",
                suitCode: "RX-0",
                imageUrlFront: "../public/gundam-ab/ab01/AB01-018_front.png",
                imageUrlBack: "../public/gundam-ab/ab01/AB01-018_back.png"
            },
            {
                name: "Unicorn Gundam 02 Banshee Norn",
                cardType: "Mobile Suit",
                msType: "Short Range",
                plType: null,
                parallel: false,
                cost: 3,
                rarity: "R",
                mobility: 160,
                longRange: 100,
                shortRange: 200,
                hp: 200,
                earthMod: "A",
                spaceMod: "A",
                desertMod: "C",
                waterMod: "B",
                series: "Gundam UC",
                mainWeapon: "Beam Saber",
                mainWeaponRange: 1,
                mainWeaponType: "Short Range",
                subWeapon: "Vulcan Gun",
                subWeaponRange: 2,
                subWeaponType: "Long Range",
                msAbility: "Rally [Defense]",
                msActiveCondition: "Manual Activation",
                msTargetType: "Area of Effect (Ally)",
                msAbilityRange: null,
                msAbilityCost: 4,
                msAbilityDesc: "For 20 seconds, all allies within a large area around the user takes reduced damage.",
                spAbilityName: "Beam Saber Strong Strike",
                spAbilityTargetType: "Single Target (Enemy)",
                spAbilityRange: 2,
                spAbilityCost: 2,
                spAbilityDamage: 3300,
                spAbilityDesc: "Deals short range damage to the target.",
                linkIds: {
                    connect: [{linkAbility: "Gundam UC"}, {linkAbility: "Psycho-Frame User"}]
                },
                set: {connect: {shortName: "AB01"}},
                setNum: "-019",
                suitCode: "RX-0",
                imageUrlFront: "../public/gundam-ab/ab01/AB01-019_front.png",
                imageUrlBack: "../public/gundam-ab/ab01/AB01-019_back.png"
            },
            {
                name: "Sinanju",
                cardType: "Mobile Suit",
                msType: "Short Range",
                plType: null,
                parallel: false,
                cost: 6,
                rarity: "P",
                mobility: 240,
                longRange: 240,
                shortRange: 480,
                hp: 500,
                earthMod: "A",
                spaceMod: "S",
                desertMod: "C",
                waterMod: "C",
                series: "Gundam UC",
                mainWeapon: "Beam Naginata",
                mainWeaponRange: 1,
                mainWeaponType: "Short Range",
                subWeapon: "Beam Rifle",
                subWeaponRange: 3,
                subWeaponType: "Long Range",
                msAbility: "Hindering Strike [Atk]",
                msActiveCondition: "Manual Activation",
                msTargetType: "Single Target (Enemy)",
                msAbilityRange: 1,
                msAbilityCost: 4,
                msAbilityDesc: "Deal damage to the target. For 20 seconds, the target's [Long Range Atk][Short Range Atk] all moderately reduced.",
                spAbilityName: "Beam Naginata Strong Strike",
                spAbilityTargetType: "Single Target (Enemy)",
                spAbilityRange: 2,
                spAbilityCost: 2,
                spAbilityDamage: 3600,
                spAbilityDesc: "Deals short range damage to the target.",
                linkIds: {
                    connect: [{linkAbility: "Gundam UC"}, {linkAbility: "Red Pride"}]
                },
                set: {connect: {shortName: "AB01"}},
                setNum: "-020",
                suitCode: "MSN-06S",
                imageUrlFront: "../public/gundam-ab/ab01/AB01-020_front.png",
                imageUrlBack: "../public/gundam-ab/ab01/AB01-020_back.png"
            },
            {
                name: "Sinanju",
                cardType: "Mobile Suit",
                msType: "Short Range",
                plType: null,
                parallel: true,
                cost: 6,
                rarity: "P",
                mobility: 240,
                longRange: 240,
                shortRange: 480,
                hp: 500,
                earthMod: "A",
                spaceMod: "S",
                desertMod: "C",
                waterMod: "C",
                series: "Gundam UC",
                mainWeapon: "Beam Naginata",
                mainWeaponRange: 1,
                mainWeaponType: "Short Range",
                subWeapon: "Beam Rifle",
                subWeaponRange: 3,
                subWeaponType: "Long Range",
                msAbility: "Hindering Strike [Atk]",
                msActiveCondition: "Manual Activation",
                msTargetType: "Single Target (Enemy)",
                msAbilityRange: 1,
                msAbilityCost: 4,
                msAbilityDesc: "Deal damage to the target. For 20 seconds, the target's [Long Range Atk][Short Range Atk] all moderately reduced.",
                spAbilityName: "Beam Naginata Strong Strike",
                spAbilityTargetType: "Single Target (Enemy)",
                spAbilityRange: 2,
                spAbilityCost: 2,
                spAbilityDamage: 3600,
                spAbilityDesc: "Deals short range damage to the target.",
                linkIds: {
                    connect: [{linkAbility: "Gundam UC"}, {linkAbility: "Red Pride"}]
                },
                set: {connect: {shortName: "AB01"}},
                setNum: "-020",
                suitCode: "MSN-06S",
                imageUrlFront: "../public/gundam-ab/ab01/AB01-020_front_p.png",
                imageUrlBack: "../public/gundam-ab/ab01/AB01-020_back_p.png"
            },
            {
                name: "Sinanju",
                cardType: "Mobile Suit",
                msType: "Short Range",
                plType: null,
                parallel: false,
                cost: 6,
                rarity: "R",
                mobility: 240,
                longRange: 140,
                shortRange: 300,
                hp: 370,
                earthMod: "A",
                spaceMod: "S",
                desertMod: "C",
                waterMod: "C",
                series: "Gundam UC",
                mainWeapon: "Beam Axe",
                mainWeaponRange: 1,
                mainWeaponType: "Short Range",
                subWeapon: "Beam Rifle",
                subWeaponRange: 3,
                subWeaponType: "Long Range",
                msAbility: "Hinder [Atk]",
                msActiveCondition: "Manual Activation",
                msTargetType: "Area of Effect (Enemy)",
                msAbilityRange: null,
                msAbilityCost: null,
                msAbilityDesc: "For 20 seconds, all enemy units in a large area around the user has their [Long Range Atk][Short Range Atk] slightly reduced.",
                spAbilityName: "Beam Axe Strong Strike",
                spAbilityTargetType: "Single Target (Enemy)",
                spAbilityRange: 2,
                spAbilityCost: 2,
                spAbilityDamage: 3400,
                spAbilityDesc: "Deals short range damage to the target.",
                linkIds: {
                    connect: [{linkAbility: "Gundam UC"}, {linkAbility: "Red Pride"}]
                },
                set: {connect: {shortName: "AB01"}},
                setNum: "-021",
                suitCode: "MSN-06S",
                imageUrlFront: "../public/gundam-ab/ab01/AB01-021_front.png",
                imageUrlBack: "../public/gundam-ab/ab01/AB01-021_back.png"
            },
            {
                name: "Kshatriya",
                cardType: "Mobile Suit",
                msType: "Long Range",
                plType: null,
                parallel: false,
                cost: 6,
                rarity: "M",
                mobility: 150,
                longRange: 450,
                shortRange: 160,
                hp: 390,
                earthMod: "B",
                spaceMod: "S",
                desertMod: "C",
                waterMod: "C",
                series: "Gundam UC",
                mainWeapon: "Chest-Mounted Mega Particle Cannon",
                mainWeaponRange: 4,
                mainWeaponType: "Long Range",
                subWeapon: "Beam Gun",
                subWeaponRange: 2,
                subWeaponType: "Short Range",
                msAbility: "Sweeping Fire [Wide Range]",
                msActiveCondition: "Manual Activation",
                msTargetType: "Area of Effect (Enemy)",
                msAbilityRange: 3,
                msAbilityCost: 3,
                msAbilityDesc: "Deals damage in a cone-shape with the target at the center.",
                spAbilityName: "Funnel Firing Barrage",
                spAbilityTargetType: "Single Target (Enemy)",
                spAbilityRange: 4,
                spAbilityCost: 3,
                spAbilityDamage: 3700,
                spAbilityDesc: "Deals long range damage to the target.",
                linkIds: {
                    connect: [{linkAbility: "Gundam UC"}, {linkAbility: "Psycho-Frame User"}]
                },
                set: {connect: {shortName: "AB01"}},
                setNum: "-022",
                suitCode: "NZ-666",
                imageUrlFront: "../public/gundam-ab/ab01/AB01-022_front.png",
                imageUrlBack: "../public/gundam-ab/ab01/AB01-022_back.png"
            },
            {
                name: "Kshatriya",
                cardType: "Mobile Suit",
                msType: "Short Range",
                plType: null,
                parallel: false,
                cost: 4,
                rarity: "C",
                mobility: 80,
                longRange: 110,
                shortRange: 200,
                hp: 240,
                earthMod: "B",
                spaceMod: "S",
                desertMod: "C",
                waterMod: "C",
                series: "Gundam UC",
                mainWeapon: "Beam Saber",
                mainWeaponRange: 1,
                mainWeaponType: "Short Range",
                subWeapon: "Beam Gun",
                subWeaponRange: 2,
                subWeaponType: "Short Range",
                msAbility: null,
                msActiveCondition: null,
                msTargetType: null,
                msAbilityRange: null,
                msAbilityCost: null,
                msAbilityDesc: null,
                spAbilityName: "Beam Saber Strong Strike",
                spAbilityTargetType: "Single Target (Enemy)",
                spAbilityRange: 2,
                spAbilityCost: 2,
                spAbilityDamage: 3200,
                spAbilityDesc: "Deals short range damage to the target.",
                linkIds: {
                    connect: [{linkAbility: "Gundam UC"}, {linkAbility: "Psycho-Frame User"}]
                },
                set: {connect: {shortName: "AB01"}},
                setNum: "-023",
                suitCode: "NZ-666",
                imageUrlFront: "../public/gundam-ab/ab01/AB01-023_front.png",
                imageUrlBack: "../public/gundam-ab/ab01/AB01-023_back.png"
            },
            {
                name: "Geara Zulu",
                cardType: "Mobile Suit",
                msType: "Mobility",
                plType: null,
                parallel: false,
                cost: 2,
                rarity: "C",
                mobility: 110,
                longRange: 100,
                shortRange: 150,
                hp: 230,
                earthMod: "A",
                spaceMod: "A",
                desertMod: "C",
                waterMod: "C",
                series: "Gundam UC",
                mainWeapon: "Beam Tomahawk",
                mainWeaponRange: 1,
                mainWeaponType: "Short Range",
                subWeapon: "Grenade Launcher",
                subWeaponRange: 3,
                subWeaponType: "Long Range",
                msAbility: "Resupply",
                msActiveCondition: "Manual Activation",
                msTargetType: "Area of Effect (Ally)",
                msAbilityRange: null,
                msAbilityCost: 4,
                msAbilityDesc: "Restores a moderate amount of HP to all ally units within a large area around the user",
                spAbilityName: "Beam Tomahawk Strong Strike",
                spAbilityTargetType: "Single Target (Enemy)",
                spAbilityRange: 2,
                spAbilityCost: 2,
                spAbilityDamage: 3100,
                spAbilityDesc: "Deals short range damage to the target.",
                linkIds: {
                    connect: [{linkAbility: "Gundam UC"}]
                },
                set: {connect: {shortName: "AB01"}},
                setNum: "-024",
                suitCode: "AMS-129",
                imageUrlFront: "../public/gundam-ab/ab01/AB01-024_front.png",
                imageUrlBack: "../public/gundam-ab/ab01/AB01-024_back.png"
            },
            {
                name: "Geara Zulu[Angelo Sauper Use]",
                cardType: "Mobile Suit",
                msType: "Long Range",
                plType: null,
                parallel: false,
                cost: 4,
                rarity: "R",
                mobility: 100,
                longRange: 300,
                shortRange: 70,
                hp: 140,
                earthMod: "A",
                spaceMod: "A",
                desertMod: "C",
                waterMod: "C",
                series: "Gundam UC",
                mainWeapon: "Large Bruno Gun Plus",
                mainWeaponRange: 4,
                mainWeaponType: "Long Range",
                subWeapon: "Beam Tomahawk",
                subWeaponRange: 1,
                subWeaponType: "Short Range",
                msAbility: "Call Reinforcement [Exterminate]",
                msActiveCondition: "Manual Activation",
                msTargetType: "Special (Self)",
                msAbilityRange: null,
                msAbilityCost: 3,
                msAbilityDesc: "Summons an ally unit with [Exterminate] typing nearby. Only 3 summoned units can be on the field at once.",
                spAbilityName: "Beam Rifle Piercing Shot",
                spAbilityTargetType: "Piercing (Enemy)",
                spAbilityRange: 4,
                spAbilityCost: 3,
                spAbilityDamage: 3300,
                spAbilityDesc: "Deals long range damage to all enemy units in a straight line.",
                linkIds: {
                    connect: [{linkAbility: "Gundam UC"}, {linkAbility: "Power of Personalized Units"}]
                },
                set: {connect: {shortName: "AB01"}},
                setNum: "-025",
                suitCode: "AMS-129",
                imageUrlFront: "../public/gundam-ab/ab01/AB01-025_front.png",
                imageUrlBack: "../public/gundam-ab/ab01/AB01-025_back.png"
            },
            {
                name: "Aile Strike Gundam",
                cardType: "Mobile Suit",
                msType: "Mobility",
                plType: null,
                parallel: false,
                cost: 5,
                rarity: "U",
                mobility: 380,
                longRange: 360,
                shortRange: 350,
                hp: 230,
                earthMod: "A",
                spaceMod: "S",
                desertMod: "C",
                waterMod: "B",
                series: "Gundam SEED",
                mainWeapon: "High Energy Beam Rifle",
                mainWeaponRange: 3,
                mainWeaponType: "Long Range",
                subWeapon: "Beam Saber",
                subWeaponRange: 1,
                subWeaponType: "Short Range",
                msAbility: "Sweeping Fire [Wide Area]",
                msActiveCondition: "Manual Activation",
                msTargetType: "Area of Effect (Enemy)",
                msAbilityRange: 3,
                msAbilityCost: 3,
                msAbilityDesc: "Deals damage in a cone-shape with the target at the center.",
                spAbilityName: "High Energy Beam Rifle Shot",
                spAbilityTargetType: "Single Target (Enemy)",
                spAbilityRange: 3,
                spAbilityCost: 2,
                spAbilityDamage: 3600,
                spAbilityDesc: "Deals long range damage to the target.",
                linkIds: {
                    connect: [{linkAbility: "Gundam SEED"}, {linkAbility: "Its Name Is Gundam"}]
                },
                set: {connect: {shortName: "AB01"}},
                setNum: "-026",
                suitCode: "GAT-X105+AQM/E-X01",
                imageUrlFront: "../public/gundam-ab/ab01/AB01-026_front.png",
                imageUrlBack: "../public/gundam-ab/ab01/AB01-026_back.png"
            },
            {
                name: "Aile Strike Gundam",
                cardType: "Mobile Suit",
                msType: "Mobility",
                plType: null,
                parallel: true,
                cost: 5,
                rarity: "U",
                mobility: 380,
                longRange: 360,
                shortRange: 350,
                hp: 230,
                earthMod: "A",
                spaceMod: "S",
                desertMod: "C",
                waterMod: "B",
                series: "Gundam SEED",
                mainWeapon: "High Energy Beam Rifle",
                mainWeaponRange: 3,
                mainWeaponType: "Long Range",
                subWeapon: "Beam Saber",
                subWeaponRange: 1,
                subWeaponType: "Short Range",
                msAbility: "Sweeping Fire [Wide Area]",
                msActiveCondition: "Manual Activation",
                msTargetType: "Area of Effect (Enemy)",
                msAbilityRange: 3,
                msAbilityCost: 3,
                msAbilityDesc: "Deals damage in a cone-shape with the target at the center.",
                spAbilityName: "High Energy Beam Rifle Shot",
                spAbilityTargetType: "Single Target (Enemy)",
                spAbilityRange: 3,
                spAbilityCost: 2,
                spAbilityDamage: 3600,
                spAbilityDesc: "Deals long range damage to the target.",
                linkIds: {
                    connect: [{linkAbility: "Gundam SEED"}, {linkAbility: "Its Name Is Gundam"}]
                },
                set: {connect: {shortName: "AB01"}},
                setNum: "-026",
                suitCode: "GAT-X105+AQM/E-X01",
                imageUrlFront: "../public/gundam-ab/ab01/AB01-026_front_p.png",
                imageUrlBack: "../public/gundam-ab/ab01/AB01-026_back_p.png"
            },
            {
                name: "Aile Strike Gundam",
                cardType: "Mobile Suit",
                msType: "Short Range",
                plType: null,
                parallel: false,
                cost: 3,
                rarity: "C",
                mobility: 140,
                longRange: 100,
                shortRange: 160,
                hp: 170,
                earthMod: "A",
                spaceMod: "S",
                desertMod: "C",
                waterMod: "B",
                series: "Gundam SEED",
                mainWeapon: "Beam Saber",
                mainWeaponRange: 1,
                mainWeaponType: "Short Range",
                subWeapon: "Beam Rifle",
                subWeaponRange: 3,
                subWeaponType: "Long Range",
                msAbility: "Rally [Defense]",
                msActiveCondition: "Manual Activation",
                msTargetType: "Area of Effect (Ally)",
                msAbilityRange: null,
                msAbilityCost: 4,
                msAbilityDesc: "For 20 seconds, all allies within a large area of the user receives slightly reduced damage.",
                spAbilityName: "Beam Saber Strong Strike",
                spAbilityTargetType: "Single Target (Enemy)",
                spAbilityRange: 2,
                spAbilityCost: 2,
                spAbilityDamage: 3200,
                spAbilityDesc: "Deals short range damage to the target.",
                linkIds: {
                    connect: [{linkAbility: "Gundam SEED"}, {linkAbility: "Its Name Is Gundam"}]
                },
                set: {connect: {shortName: "AB01"}},
                setNum: "-027",
                suitCode: "GAT-X105+AQM/E-X01",
                imageUrlFront: "../public/gundam-ab/ab01/AB01-027_front.png",
                imageUrlBack: "../public/gundam-ab/ab01/AB01-027_back.png"
            },
            {
                name: "Aegis Gundam",
                cardType: "Mobile Suit",
                msType: "Long Range",
                plType: null,
                parallel: false,
                cost: 4,
                rarity: "P",
                mobility: 140,
                longRange: 330,
                shortRange: 130,
                hp: 260,
                earthMod: "A",
                spaceMod: "A",
                desertMod: "C",
                waterMod: "B",
                series: "Gundam SEED",
                mainWeapon: "High Energy Beam Rifle",
                mainWeaponRange: 3,
                mainWeaponType: "Long Range",
                subWeapon: "Beam Saber",
                subWeaponRange: 1,
                subWeaponType: "Short Range",
                msAbility: "Piercing Fire",
                msActiveCondition: "Manual Activation",
                msTargetType: "Piercing (Enemy)",
                msAbilityRange: 4,
                msAbilityCost: 3,
                msAbilityDesc: "After charging for a moment, fires a piercing long range attack at the target, dealing damage to all enemies in the line of fire.",
                spAbilityName: "Scylla Piercing Shot",
                spAbilityTargetType: "Piercing (Enemy)",
                spAbilityRange: 4,
                spAbilityCost: 3,
                spAbilityDamage: 3500,
                spAbilityDesc: "Deals long range damage to all units in a straight line.",
                linkIds: {
                    connect: [{linkAbility: "Gundam SEED"}, {linkAbility: "Red Pride"}]
                },
                set: {connect: {shortName: "AB01"}},
                setNum: "-028",
                suitCode: "GAT-X303",
                imageUrlFront: "../public/gundam-ab/ab01/AB01-028_front.png",
                imageUrlBack: "../public/gundam-ab/ab01/AB01-028_back.png"
            },
            {
                name: "Aegis Gundam",
                cardType: "Mobile Suit",
                msType: "Long Range",
                plType: null,
                parallel: true,
                cost: 4,
                rarity: "P",
                mobility: 140,
                longRange: 330,
                shortRange: 130,
                hp: 260,
                earthMod: "A",
                spaceMod: "A",
                desertMod: "C",
                waterMod: "B",
                series: "Gundam SEED",
                mainWeapon: "High Energy Beam Rifle",
                mainWeaponRange: 3,
                mainWeaponType: "Long Range",
                subWeapon: "Beam Saber",
                subWeaponRange: 1,
                subWeaponType: "Short Range",
                msAbility: "Piercing Fire",
                msActiveCondition: "Manual Activation",
                msTargetType: "Piercing (Enemy)",
                msAbilityRange: 4,
                msAbilityCost: 3,
                msAbilityDesc: "After charging for a moment, fires a piercing long range attack at the target, dealing damage to all enemies in the line of fire.",
                spAbilityName: "Scylla Piercing Shot",
                spAbilityTargetType: "Piercing (Enemy)",
                spAbilityRange: 4,
                spAbilityCost: 3,
                spAbilityDamage: 3500,
                spAbilityDesc: "Deals long range damage to all units in a straight line.",
                linkIds: {
                    connect: [{linkAbility: "Gundam SEED"}, {linkAbility: "Red Pride"}]
                },
                set: {connect: {shortName: "AB01"}},
                setNum: "-028",
                suitCode: "GAT-X303",
                imageUrlFront: "../public/gundam-ab/ab01/AB01-028_front_p.png",
                imageUrlBack: "../public/gundam-ab/ab01/AB01-028_back_p.png"
            },
        ]
    })
}