import type { NextApiRequest, NextApiResponse } from "next";

type ResponseData = {
    id: Number,
    name: String,
    cardType: String,
    msType: String|null,
    plType: String|null,
    parallel: Boolean,
    cost: Number,
    rarity: String,
    mobility: Number,
    longRange: Number,
    shortRange: Number,
    hp: Number,
    earthMod: String|null,
    spaceMod: String|null,
    desertMod: String|null,
    waterMod: String|null,
    series: String,
    mainWeapon: String|null,
    mainWeaponRange: Number|null,
    mainWeaponType: String|null,
    subWeapon: String|null,
    subWeaponRange: Number|null,
    subWeaponType: String|null,
    msAbility: String|null,
    msTargetType: String|null,
    msAbilityCost: Number|null,
    msActiveCondition: String|null,
    msAbilityRange: Number|null,
    msAbilityDesc: String|null,
    spAbilityName: String|null,
    spAbilityTargetType: String|null,
    spAbilityRange: Number|null,
    spAbilityDamage: Number|null,
    spAbilityCost: Number|null,
    spAbilityDesc: String|null,
    linkIds: Array<Object>,
    set: String,
    setNum: String,
    suitCode: String|null,
    plAbilityName: String|null,
    plAbilityActiveCondition: String|null,
    plAbilityDesc: String|null,
    imageUrlFront: String,
    imageUrlBack: String
}

export default function handler(
    req: NextApiRequest,
    res: NextApiResponse<ResponseData>
){
    if(req.method === 'GET'){
        res.status(200).send({
            id: -1,
            name: "Gundam",
                    cardType: "Mobile Suit",
                    msType: "Short Range",
                    plType: null,
                    parallel: false,
                    cost: 4,
                    rarity: "M",
                    mobility: 200,
                    longRange: 110,
                    shortRange: 370,
                    hp: 380,
                    earthMod: "A",
                    spaceMod: "A",
                    desertMod: "C",
                    waterMod: "A",
                    series: "Mobile Suit Gundam",
                    mainWeapon: "Beam Saber",
                    mainWeaponRange: 1,
                    mainWeaponType: "Short Range",
                    subWeapon: "Beam Rifle",
                    subWeaponRange: 3,
                    subWeaponType: "Long Range",
                    msAbility: "Consecutive Attacks",
                    msActiveCondition: "Manual Activation",
                    msTargetType: "Single Target (Enemy)",
                    msAbilityRange: 2,
                    msAbilityCost: 3,
                    msAbilityDesc: "Deal damage to the target.",
                    spAbilityName: "Beam Saber Heavy Strike",
                    spAbilityTargetType: "Single Target (Enemy)",
                    spAbilityRange: 2,
                    spAbilityCost: 2,
                    spAbilityDamage: 3400,
                    spAbilityDesc: "Deal short range damage to the target.",
                    linkIds: [{linkAbility: "Mobile Suit Gundam"}, {linkAbility: "Its Name Is Gundam"}],
                    set: "AB01",
                    setNum: "-001",
                    suitCode: "RX-78-2",
                    imageUrlFront: "../public/gundam-ab/ab01/AB01-001_front.png",
                    imageUrlBack: "../public/gundam-ab/ab01/AB01-001_back.png",
                    plAbilityName: null,
                    plAbilityActiveCondition: null,
                    plAbilityDesc:null,
        });
    }
}